name: twitter
dependencies:
  - python==3.7.0
  - jupyter
  - scipy==1.1.0
  - pandas==0.23.4
  - lxml 
  - html5lib
  - requests
  - beautifulsoup4
  - matplotlib
  - seaborn==0.9.0
  #- tweepy
  #- spyder-kernels
  - pip:
    - PyYAML 
